#!/bin/bash
# Quick OpenBB CLI Examples - Run these commands after starting OpenBB

echo "======================================"
echo "OpenBB CLI Quick Start Examples"
echo "======================================"
echo ""
echo "To start OpenBB CLI, run:"
echo "  ./launch-openbb.sh"
echo ""
echo "Then try these commands inside OpenBB:"
echo ""
echo "1. GET STOCK QUOTES:"
echo "   /equity/price/quote --symbol AAPL --provider yfinance"
echo "   /equity/price/quote --symbol MSFT,GOOGL,AMZN --provider yfinance"
echo ""
echo "2. GET HISTORICAL PRICES:"
echo "   /equity/price/historical --symbol TSLA --start_date 2024-11-01 --provider yfinance"
echo ""
echo "3. GET COMPANY NEWS:"
echo "   /news/company --symbol AAPL --provider benzinga"
echo ""
echo "4. GET CRYPTO PRICES:"
echo "   /crypto/price/quote --symbol BTCUSD --provider yfinance"
echo ""
echo "5. GET ECONOMIC DATA:"
echo "   /economy/inflation --country united_states --provider fred"
echo "   /economy/gdp --country united_states --provider oecd"
echo ""
echo "6. GET MARKET MOVERS:"
echo "   /equity/discovery/gainers --provider yfinance"
echo "   /equity/discovery/losers --provider yfinance"
echo ""
echo "7. GET ETF DATA:"
echo "   /etf/price/quote --symbol SPY --provider yfinance"
echo ""
echo "8. GET TREASURY RATES:"
echo "   /fixedincome/treasury/rates --provider federal_reserve"
echo ""
echo "9. TECHNICAL INDICATORS (requires historical data first):"
echo "   /equity/price/historical --symbol AAPL --start_date 2024-10-01 --provider yfinance"
echo "   /technical/sma --data OBB0 --length 20"
echo ""
echo "10. EXPORT DATA TO CSV:"
echo "    /equity/price/historical --symbol NVDA --start_date 2024-01-01 --export csv"
echo ""
echo "======================================"
echo "TIPS:"
echo "- Use TAB for auto-completion"
echo "- Type 'help' in any menu to see available commands"
echo "- Type 'quit' or 'q' to exit"
echo "- Results are cached as OBB0, OBB1, etc."
echo "- Use --chart true to visualize data"
echo "======================================" 
